---
deployment:
  tasks:
    - export DEPLOYPATH=/home/lattessa/lattessa_app
    - /usr/local/bin/php $DEPLOYPATH/artisan config:clear
    - /usr/local/bin/php $DEPLOYPATH/artisan route:clear
    - /usr/local/bin/php $DEPLOYPATH/artisan view:clear
